### ISSUE TITLE
Nonsensical implementation of Dfsm::calcDistinguishingTraceInTree

### ISSUE THREAD

**Issue by tmlrbgfz** [agbs-uni-bremen/fsmlib-cpp#6]
Dfsm::calcDistinguishingTraceInTree always returns an empty trace.
That does not seem right.

**Comment by Sadik** [comment]
Thank you for the comment.
`Dfsm::calcDistinguishingTraceInTree` has two return statements: One in line 1403 and one at the end of the method. Consider the following Tree: 
![htree](https://user-images.githubusercontent.com/29516757/36282862-d6ae7426-12a2-11e8-9233-a58e4ab2d480.png)

The` deque q1 ` is initialized with` [a,b]`. Then it is checked whether the first element in the deque (`a`) is already distinguishing the two FsmNodes` s_i` and `s_j`. If this is the case then `a` is returned, e.i. a non-empty InputTrace. If `a` is not distinguishing the two nodes, the children of `a` are added to `q1` so that `q1` has the following elements: `[b, aa, ab]`. Then `b`is checked and if it's not distinguishing the two nodes, its children are added to the deque: `[aa, ab, ba, bb]`. When these four elements are also not distinguishing traces then we don't have a distinguishing trace in this Tree. This is where an empty trace is returned.

**Comment by tmlrbgfz** [comment]
Whoops, my bad!
Thank you for the elaborate answer!
